name: Gargantua CI
on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - main
jobs:
  lint-build-and-test:
    name: Lint, Build, and Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: setup node
        uses: actions/setup-node@v3
        with:
          node-version: '22'
          cache: 'yarn'

      - name: Install Dependencies
        run: yarn install --immutable

      - name: Lint Code
        run: yarn lint

      - name: Build Project
        run: yarn build

      - name: Run Tests
        run: yarn test
